import { getPages } from "@/sanity/sanity-utils";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Personal Portfolio Website",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // GET ALL PAGES
  const pages = await getPages();
  console.log(pages);

  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gradient-to-tr from-orange-100 via-red-100 to-purple-100 h-full max-w-5xl mx-auto py-10 p-5`}
      >
        <header className="flex justify-between items-center">
          <Link
            href="/"
            className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent font-bold text-lg"
          >
            AKIF
          </Link>
          <div className="flex items-center gap-3 text-sm text-gray-600">
            {pages.map((page) => (
              <Link
                key={page._id}
                href={`/${page.slug}`}
                className="hover:underline"
              >
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main className="py-20">{children}</main>
      </body>
    </html>
  );
}
